development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "REDISCLOUD_URL" } %>
  channel_prefix: new_blog_production
